### ISSUE TITLE
Shows Pdf Conversion Completed but Reports Error in Obs

### ISSUE THREAD

**Issue by dcb-right-fox** [L3-N0X/obsidian-marker#10]
![image](https://github.com/user-attachments/assets/8dd7715d-4e3d-4a8b-82bb-1ed6a5ae12ce)

Successfully used this for a few weeks now, then over the last weekend it only generates this fail notice 100% of attempts:

(1) Plugin reports pdf conversion is completed, but also displays conversion failed alert.

(2) Marker API successfully reports API access and process.

I've tried uninstalling/reinstalling plugin, resetting Marker API key, turning off all other Obsidian plugins with no success.  My Datalab dev account is properly funded and no other errors being reported in the log.  

Any suggestions / any more information I can provide / anything else I can try?

**Comment by L3-N0X** [comment]
I'm sorry to hear that, can you please send me your logs from obsidian?
Here you can see how: https://help.obsidian.md/Help+and+support#Capture+console+logs

I updated the plugin last week, but I didn't change anything regarding the datalab api (at least I think so). Are you using the datalab API or the self-hosted version?

The connection to the datalab API seems to work fine, so this should not be the problem.
I need the logs to help you, because I don't have the API myself.

**Comment by L3-N0X** [comment]
Never mind, I think I've found the issue. Please try Version 1.3.1 and tell me if this fixes your problem!

**Comment by dcb-right-fox** [comment]
*> Never mind, I think I've found the issue. Please try Version 1.3.1 and
tell me if this fixes your problem!*

Sure thing - will give it a go in ~60 minutes time.

*> I need the logs to help you, because I don't have the API myself.*

Happy to set you up with an API key for a day if the 1.3.1 version a fix -
will let you know shortly.

**Comment by dcb-right-fox** [comment]
Unfortunately 1.3.1 didn't fix the issue.
![image](https://github.com/user-attachments/assets/a7871d89-d050-4fc4-91ab-3bd7c304f3a8)

(1) version 1.3.1
(2) error generated, folder is created (as per options) but nothing in the folder
(3) API records that conversion took place
(4) Obs log shows no errors or warnings.

**Comment by L3-N0X** [comment]
Now it should actually be fixed, made a small mistake yesterday, sorry. Now it should actually be working again. Please check if 1.3.2 is working for you now.

**Comment by dcb-right-fox** [comment]
Confirmed as working now - many thanks for your help!
